# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price_base', models.DecimalField(decimal_places=2, help_text='Der Grundpreis f\xfcr eine Abholung bzw. den ersten Kilometer.', max_digits=4, verbose_name='Grundpreis')),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Der Preis pro gefahrenen Kilometer.', max_digits=4, verbose_name='Preis pro Km')),
                ('price_priority', models.DecimalField(decimal_places=2, editable=False, help_text='Wird derzeit noch nicht verwendet', max_digits=4, verbose_name='Zuschlag')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=1.19, help_text='Optional; standardm\xe4\xdfig 19 %.', max_digits=4, verbose_name='MwSt.')),
            ],
        ),
    ]
