# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Tarif', 'verbose_name_plural': 'Tarife'},
        ),
        migrations.AlterField(
            model_name='rate',
            name='price_priority',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Wird derzeit noch nicht verwendet', max_digits=4, null=True, verbose_name='Zuschlag'),
        ),
    ]
