# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0002_auto_20160319_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.CharField(max_length=40, verbose_name='Ansprechpartner')),
                ('from_company', models.CharField(blank=True, max_length=40, verbose_name='Firma')),
                ('from_telephone', models.CharField(max_length=20, verbose_name='Telefonnummer')),
                ('from_street', models.CharField(max_length=30, verbose_name='Stra\xdfe')),
                ('from_streetnumber', models.CharField(max_length=5, verbose_name='Hausnummer')),
                ('from_zipcode', models.PositiveSmallIntegerField(verbose_name='PLZ')),
                ('from_comment', models.CharField(help_text='Geb\xe4ude, Stockwerk, o.\xc4.', max_length=40, verbose_name='Bemerkung')),
                ('timeframe_pickup', models.TimeField(choices=[('0800', ' 8:00 \u2013  9:00'), ('0900', ' 9:00 \u2013 10:00'), ('1000', '10:00 \u2013 11:00'), ('1100', '11:00 \u2013 12:00'), ('1200', '12:00 \u2013 13:00'), ('1300', '13:00 \u2013 14:00'), ('1400', '14:00 \u2013 15:00'), ('1500', '15:00 \u2013 16:00'), ('1600', '16:00 \u2013 17:00'), ('1700', '17:00 \u2013 18:00'), ('1800', '18:00 \u2013 19:00')], verbose_name='Zeitfenster Abholung')),
                ('to_person', models.CharField(max_length=40, verbose_name='Ansprechpartner')),
                ('to_company', models.CharField(blank=True, max_length=40, verbose_name='Firma')),
                ('to_telephone', models.CharField(max_length=20, verbose_name='Telefonnummer')),
                ('to_street', models.CharField(max_length=30, verbose_name='Stra\xdfe')),
                ('to_streetnumber', models.CharField(max_length=5, verbose_name='Hausnummer')),
                ('to_zipcode', models.PositiveSmallIntegerField(verbose_name='PLZ')),
                ('to_comment', models.CharField(help_text='Geb\xe4ude, Stockwerk, o.\xc4.', max_length=40, verbose_name='Bemerkung')),
                ('timeframe_dropoff', models.TimeField(choices=[('0800', ' 8:00 \u2013  9:00'), ('0900', ' 9:00 \u2013 10:00'), ('1000', '10:00 \u2013 11:00'), ('1100', '11:00 \u2013 12:00'), ('1200', '12:00 \u2013 13:00'), ('1300', '13:00 \u2013 14:00'), ('1400', '14:00 \u2013 15:00'), ('1500', '15:00 \u2013 16:00'), ('1600', '16:00 \u2013 17:00'), ('1700', '17:00 \u2013 18:00'), ('1800', '18:00 \u2013 19:00')], verbose_name='Zeitfenster Auslieferung')),
                ('distance', models.PositiveSmallIntegerField(null=True, verbose_name='Distanz')),
                ('package_detail', models.CharField(blank=True, max_length=40, verbose_name='Was wird transportiert?')),
                ('packages_s', models.PositiveSmallIntegerField(default=0, verbose_name='Packst\xfccke klein')),
                ('packages_m', models.PositiveSmallIntegerField(default=0, verbose_name='Packst\xfccke mittel')),
                ('packages_l', models.PositiveSmallIntegerField(default=0, verbose_name='Packst\xfccke gro\xdf')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('ordered', models.DateTimeField(auto_now_add=True, verbose_name='Bestelldatum')),
                ('delivered', models.DateTimeField(blank=True, null=True, verbose_name='Auslieferungsdatum')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
            },
        ),
    ]
