# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_comment',
            field=models.CharField(blank=True, help_text='Geb\xe4ude, Stockwerk, o.\xc4.', max_length=40, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_comment',
            field=models.CharField(blank=True, help_text='Geb\xe4ude, Stockwerk, o.\xc4.', max_length=40, verbose_name='Bemerkung'),
        ),
    ]
