# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_streetnumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_streetnumber',
        ),
        migrations.AlterField(
            model_name='order',
            name='from_person',
            field=models.CharField(max_length=40, verbose_name='Ansprechpartner_in'),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_street',
            field=models.CharField(max_length=30, verbose_name='Stra\xdfe und Hausnummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNFINISHED', '0. unfertig'), ('NEW', '1. neu'), ('CONFIRMED', '2. best\xe4tigt'), ('PICKED_UP', '3. abgeholt'), ('DELIVERED', '4. ausgeliefert'), ('CANCELED', 'x. storniert')], default='UNFINISHED', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_person',
            field=models.CharField(max_length=40, verbose_name='Ansprechpartner_in'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_street',
            field=models.CharField(max_length=30, verbose_name='Stra\xdfe und Hausnummer'),
        ),
    ]
