# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0007_auto_20160323_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_telephone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_telephone',
        ),
        migrations.AddField(
            model_name='order',
            name='from_phone_no',
            field=models.CharField(default='+49', max_length=15, verbose_name='Telefonnummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='to_phone_no',
            field=models.CharField(default='+49', max_length=15, verbose_name='Telefonnummer'),
            preserve_default=False,
        ),
    ]
