# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0008_auto_20160323_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(choices=[('PICKUP', 'Abholung'), ('DROPOFF', 'Auslieferung')], default='PICKUP', max_length=8, verbose_name='Barzahlung bei'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='from_phone_no',
            field=models.CharField(default='+49 ', max_length=15, validators=[django.core.validators.RegexValidator(message="Die Telefonnummer bitte nach diesem Format eingeben: '+49 000 00000'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefonnummer'),
        ),
    ]
