# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0009_auto_20160323_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=11.07, help_text='Der Preis dieses Auftrags inkl. MwSt.', max_digits=4, verbose_name='Preis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(choices=[('PICKUP', 'Abholung'), ('DROPOFF', 'Auslieferung')], default='PICKUP', max_length=8, verbose_name='Barzahlung bei'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ecourier_id',
            field=models.PositiveIntegerField(blank=True, help_text='Sobald diese Tour in eCourier \xfcbernommen wurde, sollte hier die         entsprechende Tournummer hinterlegt sein. Der Status `best\xe4tigt` kann nur         dann erteilt werden, wenn eine Tournummer angegeben wurde.', null=True, verbose_name='Tournummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_phone_no',
            field=models.CharField(default='+49 ', max_length=15, validators=[django.core.validators.RegexValidator(message="Die Telefonnummer bitte nach diesem Format eingeben: '+49 000 00000'.", regex='^\\+?1?[ \\d]{9,15}$')], verbose_name='Telefonnummer'),
        ),
    ]
