# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0011_auto_20160329_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.ForeignKey(help_text='Der Tarif wird automatisch anhand der Packst\xfccke berechnet, kann         aber \xfcberschrieben werden.', null=True, on_delete=django.db.models.deletion.CASCADE, to='fwk.Rate', verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Der Preis dieses Auftrags inkl. Mehrwertsteuer. Wird automatisch anhand         des Tarifs und der Strecke berechnet, kann aber \xfcberschrieben werden.', max_digits=4, null=True, verbose_name='Preis'),
        ),
    ]
