# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwk', '0014_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='directions_json',
            field=models.TextField(blank=True, verbose_name='Maps API JSON result'),
        ),
    ]
